heat_template_version: 2014-10-16

description: Group for auto scaling

resources:
  group:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: 60
      desired_capacity: 1
      max_size: 2
      min_size: 1
      resources:
        type: OS::Nova::Server::Worker

  scaleup_policy:
    type: OS::Heat::ScalingPolicy
      properties: 
        adjustment_type: change_in_capacity
        auto_scaling_group_id: { get_resource: group }
        cooldown: 60
        scaling_adjustment: 1
        type: webhook

  scaledown_policy:
    type: OS::Heat::ScalingPolicy
      properties: 
        adjustment_type: change_in_capacity
        auto_scaling_group_id: { get_resource: group }
        cooldown: 60
        scaling_adjustment: -1
        type: webhook

  scale_up_webhook:
    type: OS::AutoScale::WebHook
    properties:
      auto_scaling_policy_id: { get_resource: scaleup_policy }
 
  scale_down_webhook:
    type: OS::AutoScale::WebHook
    properties:
      auto_scaling_policy_id: { get_resource: scaledown_policy }

outputs:
  "Scale UP webhook":
    value: { get_attr: [ scale_up_webhook, executeUrl ] }

  "Scale DOWN webhook":
    value: { get_attr: [ scale_down_webhook, executeUrl ] }


