heat_template_version: 2014-10-16

description: Group for auto scaling

resources:

  master: 
    type: OS::Nova::Server::Master

  group:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: 60
      desired_capacity: 1
      max_size: 3
      min_size: 1
      resource:
        type: OS::Nova::Server::Worker

  scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties: 
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: group }
      cooldown: 60
      scaling_adjustment: 1
      #type: webhook

  scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties: 
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: group }
      cooldown: 60
      scaling_adjustment: -1
      #type: webhook

outputs:
  "Scale UP webhook":
    value: { get_attr: [ scaleup_policy, signal_url ] }

  "Scale DOWN webhook":
    value: { get_attr: [ scaledown_policy, signal_url ] }


