heat_template_version: 2014-10-16

description: Group for auto scaling

resources:
  group:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: 60
      desired_capacity: 1
      max_size: 2
      min_size: 1
      resources:
        type: OS::Nova::Server::Worker

  scaleup_policy:
    type: OS::Heat:ScalingPolicy
      properties: 
        adjustment_type: change_in_capacity
        auto_scaling_group_id: { get_resource: group }
        cooldown: 60
        scaling_adjustment: 1

  scaledown_policy:
    type: OS::Heat:ScalingPolicy
      properties: 
        adjustment_type: change_in_capacity
        auto_scaling_group_id: { get_resource: group }
        cooldown: 60
        scaling_adjustment: -1

  cpu_alarm_high:
    type: OS::Ceilometer::Alarm
    properties:
      meter_name: cpu_util
      statistic: avg
      period: 60
      evaluation_periods: 1
      threshold: 60
      alarm_actions:
        - {get_attr: [scaleup_policy, alarm_url]}
      comparison_operator: gt
 
  cpu_alarm_low:
    type: OS::Ceilometer::Alarm
    properties:
      meter_name: cpu_util
      statistic: avg
      period: 60
      evaluation_periods: 1
      threshold: 30
      alarm_actions:
        - {get_attr: [scaledown_policy, alarm_url]}
      comparison_operator: lt

