resource_registry:
    "OS::Nova::Server::Master": "/home/micke/Dokument/CloudProject/Heat\ Autoscale/MasterTemplate.yaml"
    "OS::Nova::Server::Worker": "/home/micke/Dokument/CloudProject/Heat\ Autoscale/WorkerTemplate.yaml"
