heat_template_version: 2014-10-16

description: Template for creating a master VM

# Declare various parameters
parameters:

  image:
    type: string
    label: Image name or ID
    description: Image to be used for worker VM (Ubuntu 16.04 LTS - Xenial Xerus)
    #default: 7211d89e-6b27-4986-9f53-f48868da6d0c
    default: 966cb731-025c-4911-bb79-2b1c046f1817

  flavor:
    type: string
    label: Flavor 
    description: Type of VM (i.e. flavor) to use
    default: ssc.small

  key:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
    default: Group12_Key

  public_network:
    type: string
    label: Public network name or ID
    description: Public network with floating IP addresses (Public External IPv4)
    default: Public External IPv4 Network

  private_network: 
    type: string
    label: Private network
    description: Group 12 Internal Network
    #default: Group 12 Internal Network
    default: SNIC 2017/13-45 Internal IPv4 Network

# Resource allocation
resources:

  cluster_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: cluster_sg
      rules:
        - protocol: icmp
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22

  #private_network:
  #  type: OS::Neutron::Net

  #private_subnet:
  #  type: OS::Neutron::Subnet
  #  properties:
  #    network_id: { get_resource: private_network }
  #    cidr: 10.10.10.0/24
  #    dns_nameservers:
  #      - 130.238.164.6
  #      - 130.238.4.133
  #      - 130.238.7.10
  #      - 130.239.1.90
  #      - 129.16.1.53

  #router:
  #  type: OS::Neutron::Router
  #  properties:
  #    external_gateway_info:
  #      network: { get_param: public_network }

  #router-interface:
  #  type: OS::Neutron::RouterInterface
  #  properties:
  #    router_id: { get_resource: router }
  #    subnet: { get_resource: private_subnet }

  port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: private_network }
      security_groups:
        - { get_resource: cluster_sg }

  #volume:
  #  type: OS::Cinder::Volume
  #  properties:
  #    size: 5

  server:
    type: OS::Nova::Server
    properties:
      name: Worker
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      #security_groups:
      #  - { get_resource: cluster_sg }
      networks:
        - port: { get_resource: port }
      #block_device_mapping:
      #  - device_name: vda
      #    delete_on_termination: true
      #    volume_id: { get_resource: volume }
      user_data: |
        #!/bin/sh
        touch /home/ubuntu/Group12_Key.pem
        echo "-----BEGIN RSA PRIVATE KEY----- MIIEpAIBAAKCAQEA12yaBRFLyTPLQDbq+/6s74ErPTOynzyWdnjn2hFZh5CJz/CfwL6KxD8+7C9TBapZ+mnFjsE+DjFvsomF/S2qzMEeZTLif/D8+ksZ/Pgmpq4R+9HeZn4mNolIUslZrc57pXvt+4ezU8fbvgaVgdktSdLZyb277FV5vGRWPrN5MvdEoyFnIvOSEs2p0lMoNjxezVdqskMgaD1udgE0mak/VVKpYIy5tSu3HQKDlB/jmwEb5w43wFklOIMbjdrnMeWFBF3xTlIZ1oR5lXAmIRh8nsjrbKi1jXp/yS5QUfbJU8moAmd+xFku97Zkhzpm7KsyKRV7btD76EHBzndRPhe95wIDAQABAoIBAQC7mWfHYfiNjv1BPpIEQRR4vhPZiFvVL/4XzdKapOFCnSxmWTXFtClEHY++PrgeBuu0lsfkOYTA92w+HmUAxfQnu0Ws+1Mj98lWbnCDS9bc8FnY4jq7JsBAXe0NqyrdoSMsSXBFyzbvjuxd333zRh2aXHQsq34roYQR+47fq4uwROvuWG+4LTrp4q2vzgioRblIyEFOG+OXEeDuNsX5e2aWrTIom2IMhj3tVMLF+JtVl2MFk1l2flMOrdBpEStYIGKM61NlY5XrVQnXf1oyC30HTUOmH3jdSGYh+gxTjIJ0OGtAEDf4YWJbKd2DhTuwJ52VNolJ1tgJxdz5l7IGOcaBAoGBAPCRIvfF/YbxQ5HMkcMtCMvnylrNgmOk3/2/FTzKtFLufiP/JBANsa6GpOgST/f5z/slPqzNBCgDGUfGNS0lB79n9zrN2XHb2PwsAO4nDFSUlEjv96QzEFjQKcZ0Si5xF4eYlB6VhWzc8HqBCt/C+1gOJ4Kxf/4W9XFoavt6PoRDAoGBAOU+ivemUpyTKRmXG1rjYu8yxH6IZhXjD/c1jzlCtsVr+wV2Tf0WCRgSzRBxQRgib4dBvwpL3Ci2zxjvL1wifOhb9lI8wwem8CZMweOR9PqrWkOqQEBgXaYsMC6Dx6KPwPw0Ka2C5gLbDybAoRHwnaH+/jK6KG7+mAAFETwnH7eNAoGAOVFrcnvDJ2bOwatrQ4S0ZtkIdtAmdBVxpSTlK4HkqynV9j+xWP3aSwobuou6cAweiOlb4JJMnjf2ywon22TKTsm3t1Qari1CqvrVEelN380y85nxeDcOewrGGVnV3vDlOVKaYBsiGkkeJyId9Cih+F4O/e3K4ECaJHZLnzWGNb8CgYEAsSDoI34h6tVSNnGpM0rq0MO7S8F8j4DIf0ylA6tmqZhLdub4T4tNL4qnZAL+NvW0kx/bysreq57E2hFF2LzVInycEOLeFvWILS+1yG6oiV8I+at8xcEv2wvdlrM/9313sedkJKs1qhM0286PJdtzEQ6DvxJT159kNu+zZ3UbbqkCgYAxJzenM9qjdPG+8mhnEuQKFADj7Bvi2cE++8/NRGvweQAPHMlvYcSSPMEKYYR7O7aKnKn1trLaSnbkdt3DYbNetyE2a+S2Obq/MTDo6/8JVkOgvVuvhszj7Y8gk8kyzpmnVkhawWew3egurtHiSiK4K6Y0vs2NxTy5y9HjCw/nEQ==-----END RSA PRIVATE KEY-----" >> /home/ubuntu/Group12_Key.pem
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDXbJoFEUvJM8tANur7/qzvgSs9M7KfPJZ2eOfaEVmHkInP8J/AvorEPz7sL1MFqln6acWOwT4OMW+yiYX9LarMwR5lMuJ/8Pz6Sxn8+CamrhH70d5mfiY2iUhSyVmtznule+37h7NTx9u+BpWB2S1J0tnJvbvsVXm8ZFY+s3ky90SjIWci85ISzanSUyg2PF7NV2qyQyBoPW52ATSZqT9VUqlgjLm1K7cdAoOUH+ObARvnDjfAWSU4gxuN2ucx5YUEXfFOUhnWhHmVcCYhGHyeyOtsqLWNen/JLlBR9slTyagCZ37EWS73tmSHOmbsqzIpFXtu0PvoQcHOd1E+F73n" >> /home/ubuntu/.ssh/authorized_keys 
      user_data_format: RAW

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network }

  floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_resource: port }


outputs:
  instance_name:
    description: Name of the instance
    value: { get_attr: [server, name] }
  instance_ip:
    description: IP address of the instance
    value: { get_attr: [server, first_address, floating_ip, floating_ip_address] }
